@ECHO OFF
CLS
TITLE Diergasies Sistimatos
SETLOCAL

CALL:MENU

:MENU
	CLS
	ECHO 1 Emfanisi diergasiwn 
	ECHO 2 Eleghos gia diergasia
	ECHO 3 Ektipwsi diergasiwn se arxeio
	ECHO 4 Exodos
	ECHO Epilexte ena programma (1,2,3) 4 Exodos
	SET /P EPILOGI=
	IF "%EPILOGI%"=="" GOTO:MENU
	IF %EPILOGI% LSS 1 GOTO:MENU
	IF %EPILOGI% GEQ 5 GOTO:MENU
	IF %EPILOGI% EQU 1 GOTO:TASK_DISPLAY
	IF %EPILOGI% EQU 2 GOTO:PROGRAM_REGISTER
	IF %EPILOGI% EQU 3 GOTO:TASK_PRINTER
	IF %EPILOGI% EQU 4 GOTO:EXODOS

:TASK_DISPLAY
    CLS
    TASKLIST | MORE
    PAUSE
    CALL:MENU

:PROGRAM_REGISTER
   CLS
   ECHO Eisagete to onoma enws programmatos h diergasias
   SET /P PROGRAM_NAME=
IF "%PROGRAM_NAME%"=="" (GOTO:PROGRAM_REGISTER) ELSE (GOTO:PROGRAM_SCANNER)
   GOTO:EOF  
   
:PROGRAM_SCANNER
   IF %PROGRAM_NAME% EQU +%PROGRAM_NAME% (GOTO:PROGRAM_REGISTER) 
   ECHO Eleghos gia %PROGRAM_NAME%
   TASKLIST | FIND /I "%PROGRAM_NAME%"> NUL
   IF %ERRORLEVEL% EQU 1 (GOTO:NOT_ACTIVE) ELSE (GOTO:ACTIVE)
   GOTO:EOF

:NOT_ACTIVE
   CLS
   ECHO To programma %PROGRAM_NAME% den ekteleitai
   PAUSE
   CALL:MENU
 
:ACTIVE
   CLS
   ECHO To programma %PROGRAM_NAME% ekteleitai
   TASKLIST | FIND /I "%PROGRAM_NAME%"
   PAUSE
   ECHO Termatismos Programmatos %PROGRAM_NAME%
   TASKLIST -M | FIND /I "%PROGRAM_NAME%"
   ECHO 1)Nai
   ECHO 2)Ohi
   SET /P TERMATISMOS=
   IF "%TERMATISMOS%"==""  GOTO:ACTIVE
	IF %TERMATISMOS% LSS 1 GOTO:ACTIVE
	IF %TERMATISMOS% GEQ 3 GOTO:ACTIVE	
 	IF %TERMATISMOS% EQU 1 GOTO:KILL_TASK
	IF %TERMATISMOS% EQU 2 GOTO:MENU

:KILL_TASK
  CLS
  TASKKILL /IM %PROGRAM_NAME% >NUL
  IF %ERRORLEVEL% EQU 1 (GOTO:KILL_TASK_EXE)
    
:KILL_TASK_EXE
  CLS
  SET EXT=.exe
  SET PRNAME=%PROGRAM_NAME%%EXT% 
  TASKKILL /IM %PRNAME% >NUL
  CALL:MENU
 
  
:TASK_PRINTER
  IF EXIST TASKS.TXT DEL TASKS.TXT
  TASKLIST > TASKS.TXT
  NOTEPAD TASKS.TXT
  DEL TASKS.TXT
  PAUSE
  CALL:MENU

:EXODOS
  CLS
  ECHO BYE BYE
  EXIT
ENDLOCAL
